### Create Team
@teamName = Test Team 1
@teamDescription = Test première teams
POST {{apiUrl}}/teams
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "{{teamName}}",
  "description": "{{teamDescription}}"
}

### Get All
@teamId = 1
GET localhost:8080/teams/{{teamId}}
Authorization: Bearer {{token}}