### Create Team
@teamName = Test Team 1
@teamDescription = Test première teams
POST {{apiUrl}}/teams
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "{{teamName}}",
  "description": "{{teamDescription}}"
}

### Get All
GET {{apiUrl}}/teams
Authorization: Bearer {{token}}

### Get team by ID
@teamId = 1
GET {{apiUrl}}/teams/{{teamId}}
Authorization: Bearer {{token}}