ktor:
  development: true
  deployment:
    port: 8080
  application:
    modules:
      - com.crackling.ApplicationKt.module

jwt:
  issuer: "crackling-api"
  audience: "crackling_app"
  realm: "ktor sample app"
  secret: "secret"

database:
  url: "jdbc:sqlserver://192.168.1.100:1433;database=crackling"
  driver: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
  username: $DB_USER
  password: $DB_PASS
