openapi: 3.1.0
info:
  title: Crackling API
  description: Crackling API
  version: 0.0.1
servers:
  - url: 'http://localhost:8080'
    description: Local server for test
tags:
  - name: Misc
    description: Route that aren't part of the API functionalities
paths:
  /helloWorld:
    get:
      summary: Test the API
      description: Test the API by asking a Hello World
      tags:
        - Misc
      responses:
        200:
          description: Hello world message
          content:
            plain/text:
              example: Hello World
  /teams:
    get:
      summary: Get multiple Teams
      description: Get all teams or a specific teams filtered by name
      parameters:
        - name: name
          description: The name of the team to find
          in: query
          required: false
          content:
            schema:
              type: string
      responses:
        200:
          description: Teams found on database
          content: 
            application/json:
              schema:
                $ref: "#/components/schemas/TeamDTO"
              examples: 
                Get all:
                  summary: Get all teams
                  value: |
                    [
                      {"id": 1, "name": "Team 1", "description": "My Team 1"},
                      {"id": 2, "name": "Team 2", "description": "My Team 2"}
                    ]
                Get by name:
                  summary: Retrieve a team by its name
                  value: {"id": 2, "name": "Team 2", "description": "My Team 2"}

components: 
  schemas: 
    TeamDTO:
      type: object
      properties: 
        id:
          type: integer
          description: The id of the Team. Optional
        name:
          type: string
          description: The name of the Team.
        description:
          type: string
          description: The description of the Team.
      required:
        - name
  examples: 
    TeamId:
      summary: Team with id
      value: {"id": 1, "name": "Team"}